# scripts/local_paths.example.tcl
# Copy this file to scripts/local_paths.tcl and edit the paths for your machine.
# scripts/local_paths.tcl is intentionally ignored by Git because it contains
# local absolute paths.

# Latest Vivado bitstream. Required by scripts/run_full.tcl.
set AD7606_BIT_FILE "D:/BaiduNetdiskDownload/hellovitis/hello.runs/impl_1/system_top.bit"

# PS initialization Tcl generated by the Vitis platform build.
set AD7606_PS7_INIT "D:/BaiduNetdiskDownload/hellovitis/platform_hello/export/platform_hello/hw/ps7_init.tcl"

# Application ELF generated by the Vitis application build.
set AD7606_ELF_FILE "D:/BaiduNetdiskDownload/hellovitis/hello_world/build/hello_world.elf"
